image: node:latest

stages:
  - deploy

cache:
  paths:
    - node_modules/
    - functions/node_modules/
  key: '$CI_BUILD_REPO'

deploy-development:
  stage: deploy
  only:
    - development
  variables:
    ENV_MODE: 'DEV'
  script:
    - npm install -g firebase-tools
    - firebase use development
    - npm install -g @quasar/cli
    - npm install
    - npm install core-js@2.6.9
    - quasar build
    - cd functions
    - npm install
    - npm run compile
    - cd ..
    - firebase functions:config:set
      sa.email=$DEV_SERVICE_ACCOUNT_EMAIL
      oauth2.client_id=$DEV_G_OAUTH2_CLIENT_ID
      oauth2.client_secret=$DEV_G_OAUTH2_CLIENT_SECRET
      frontapp.token=$DEV_FRONTAPP_TOKEN
      slack.client_id=$DEV_SLACK_CLIENT_ID
      slack.client_secret=$DEV_SLACK_CLIENT_SECRET
      slack.oauth_redirect=$DEV_SLACK_OAUTH_REDIRECT_URI
      slack.verification_token=$DEV_SLACK_VERIFICATION_TOKEN
      mavrik.base_url=$DEV_MAVRIK_CRM_BASE_URL
      mavrik.confirmation_path=$DEV_MAVRIK_CRM_CONFIRMATION_PATH
      sendgrid.api_key=$DEV_SENDGRID_API_KEY
      cloudfunction.base_url=$DEV_CLOUD_FUNCTION_BASE_URL
      nylas.client_id=$DEV_NYLAS_CLIENT_ID
      nylas.client_secret=$DEV_NYLAS_CLIENT_SECRET
      --token $DEV_FIREBASE_TOKEN
    - firebase deploy
      --non-interactive
      --token $DEV_FIREBASE_TOKEN
      -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID"

deploy-staging:
  stage: deploy
  only:
    - staging
  variables:
    ENV_MODE: 'STAGING'
  script:
    - npm install -g firebase-tools
    - firebase use staging
    - npm install -g @quasar/cli
    - npm install
    - npm install core-js@2.6.9
    - quasar build
    - cd functions
    - npm install
    - npm run compile
    - cd ..
    - firebase functions:config:set
      sa.email=$STAGING_SERVICE_ACCOUNT_EMAIL
      oauth2.client_id=$STAGING_G_OAUTH2_CLIENT_ID
      oauth2.client_secret=$STAGING_G_OAUTH2_CLIENT_SECRET
      frontapp.token=$STAGING_FRONTAPP_TOKEN
      slack.client_id=$STAGING_SLACK_CLIENT_ID
      slack.client_secret=$STAGING_SLACK_CLIENT_SECRET
      slack.oauth_redirect=$STAGING_SLACK_OAUTH_REDIRECT_URI
      slack.verification_token=$STAGING_SLACK_VERIFICATION_TOKEN
      mavrik.base_url=$STAGING_MAVRIK_CRM_BASE_URL
      mavrik.confirmation_path=$STAGING_MAVRIK_CRM_CONFIRMATION_PATH
      sendgrid.api_key=$STAGING_SENDGRID_API_KEY
      cloudfunction.base_url=$STAGING_CLOUD_FUNCTION_BASE_URL
      nylas.client_id=$STAGING_NYLAS_CLIENT_ID
      nylas.client_secret=$STAGING_NYLAS_CLIENT_SECRET
      --token $STAGING_FIREBASE_TOKEN
    - firebase deploy
      --non-interactive
      --token $STAGING_FIREBASE_TOKEN
      -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID"

deploy-prod:
  stage: deploy
  only:
    - master
  variables:
    ENV_MODE: 'PRODUCTION'
  script:
    - npm install -g firebase-tools
    - firebase use prod
    - npm install -g @quasar/cli
    - npm install
    - npm install core-js@2.6.9
    - quasar build
    - cd functions
    - npm install
    - npm run compile
    - cd ..
    - firebase functions:config:set
      sa.email=$SERVICE_ACCOUNT_EMAIL
      oauth2.client_id=$G_OAUTH2_CLIENT_ID
      oauth2.client_secret=$G_OAUTH2_CLIENT_SECRET
      frontapp.token=$FRONTAPP_TOKEN
      slack.client_id=$SLACK_CLIENT_ID
      slack.client_secret=$SLACK_CLIENT_SECRET
      slack.oauth_redirect=$SLACK_OAUTH_REDIRECT_URI
      slack.verification_token=$SLACK_VERIFICATION_TOKEN
      mavrik.base_url=$MAVRIK_CRM_BASE_URL
      mavrik.confirmation_path=$MAVRIK_CRM_CONFIRMATION_PATH
      sendgrid.api_key=$SENDGRID_API_KEY
      cloudfunction.base_url=$CLOUD_FUNCTION_BASE_URL
      nylas.client_id=$NYLAS_CLIENT_ID
      nylas.client_secret=$NYLAS_CLIENT_SECRET
      --token $FIREBASE_TOKEN
    - firebase deploy
      --non-interactive
      --token $FIREBASE_TOKEN
      -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID"
